### PR TITLE
Added Fibonacci program in JAVA language

### PR DESCRIPTION
**Pull request by Ashank16**

### CODE REVIEW

**Comment by Harsh-Udai** [comment]
@Ashank16  don't delete the files of other people, make new pr

**Comment by Ashank16** [comment]
> @Ashank16 don't delete the files of other people, make new pr

Hi @HarshUdai , this is my first time and I just followed the steps mentioned.
After cloning the repo I checked the status and the deleted file was showing before I even commited my file.
Please tell if I am wrong as I am a newbie and want to learn.
And I will definitely make a new PR.
Thanks :)

**Comment by Harsh-Udai** [comment]
@Ashank16 , okay no problem.

- fork this repo.
- make a new folder in contribution folder.(of your name)
- add files or any code.
- make pull request.


for more explanation-
go to contrinution folder of this repo and read the readme file.(this will definitely help you)
Thanks

**Comment by Ashank16** [comment]
> @Ashank16 , okay no problem.
> 
> * fork this repo.
> * make a new folder in contribution folder.(of your name)
> * add files or any code.
> * make pull request.
> 
> for more explanation-
> go to contrinution folder of this repo and read the readme file.(this will definitely help you)
> Thanks

Hi @HarshUdai  I deleted my previous repo then again forked the repository. After cloning the repository to my local machine and checking the git status, this is coming..
image
What should I do??
If I will add my folder and then commit then the same thing will happen again. Please tell as I cannot figure this out. It would be of great help!!!

**Comment by Harsh-Udai** [comment]
@Ashank16  ok that file is deleted, no issue.

**Comment by Ashank16** [comment]
> @Ashank16 ok that file is deleted, no issue.

Thanks @HarshUdai

**Pull request merged**
