### PR TITLE
Added Pattern.java and Armstrong.java

### PR DESCRIPTION
**Pull request by Ashank16**
#### 2 programs added

### CODE REVIEW

**Comment by Harsh-Udai** [comment]
@Ashank16 , go to (https://network-jklu.web.app/) website and register yourself, so that your name will appear in the contribution graph.

**Comment by Ashank16** [comment]
> @Ashank16 , go to (https://network-jklu.web.app/) website and register yourself, so that your name will appear in the contribution graph.

Hey @HarshUdai , I am not from jklu-jaipur. Should I still register in the website???

**Comment by Harsh-Udai** [comment]
@Ashank16  yes, you can register.

**Comment by Ashank16** [comment]
> @Ashank16 yes, you can register.

Ok, will do that!!

**Comment by Ashank16** [comment]
> > @Ashank16 yes, you can register.
> 
> Ok, will do that!!

done :)

**Pull request merged**
