### PR TITLE
Hacktoberfest

### PR DESCRIPTION
**Pull request by aakashmittal03**

### CODE REVIEW

**Comment by Harsh-Udai** [comment]
@aakashmittal03  don't add pdf file, you can add txt file also.

**Comment by aakashmittal03** [comment]
@HarshUdai so do i have to repeat whole process

**Comment by Harsh-Udai** [comment]
@aakashmittal03  i think it does not require more time,

**Comment by aakashmittal03** [comment]
@HarshUdai can u pls  elaborate

**Comment by Harsh-Udai** [comment]
@aakashmittal03 you have made some code in this pr, try to add the original code file , does not make any pdf.
okay , no issue i am merging your request.

**Comment by aakashmittal03** [comment]
@HarshUdai thanks

**Pull request merged**
