### PR TITLE
Create helloworld.js

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Harsh-Udai** [comment]
@Fonta22 go to (https://network-jklu.web.app/) and register yourself, so that your profile/name will appear on the graph.

**Comment by ghost** [comment]
Done :) also, the registiring page is made with particles.js? @HarshUdai

**Comment by Harsh-Udai** [comment]
Thanks, @Fonta22 the front page is made with amCharts.js

**Comment by ghost** [comment]
Oh ok😅 looks so cool @HarshUdai

**Pull request merged**
