### PR TITLE
charan tej

### PR DESCRIPTION
**Pull request by charan-143**

### CODE REVIEW

**Comment by dev-essbee** [comment]
@charan-143 , Add some content to the file.

**Comment by charan-143** [comment]
ok sir.
I will look in to that.
________________________________

**Comment by Harsh-Udai** [comment]
@charan-143  add your file inside the contribution folder.

**Comment by charan-143** [comment]
Brother,
I  don't know how to add or upload into th file .Can u help me in this process.

thank you

________________________________

**Comment by charan-143** [comment]
34073786_403692300098275_6531046532949475328_n

**Review by charan-143 — COMMENTED** [review]
[python_tutorial.pdf](https://github.com/jklu-jaipur/jklu-fraternity-network/files/5416703/python_tutorial.pdf)

**Comment by charan-143** [comment]
Got it. Done

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
